data_dir: data
output_dir: output
simulation:
  end_date: '20221130'
  initial_capital: 500000.0
  slippage_pct: 0.0008
  start_date: '20221101'
  transaction_fee_pct: 0.0001
strategy:
  xml_path: strategies/atm_straddle_strategy.xml
